blank_issues_enabled: false
contact_links:
  - name: Questions / Usage discussions
    url: https://github.com/Bl4cky99/caddy-redirector/discussions
    about: Please use Discussions for Q&A, how-to, and general guidance.
