name: docker

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  docker:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Lowercase image name
        id: meta
        run: |
          IMAGE="${{ env.IMAGE_NAME }}"
          echo "image=${IMAGE,,}" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta_tags
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.meta.outputs.image }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=mocker
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.description=Declarative mock HTTP API server

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta_tags.outputs.tags }}
          labels: ${{ steps.meta_tags.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
